name: CI

on:
  push:
    branches:
      - main
      - master

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2', '3.3', '3.4']
        rails: ['7.2', '8.0']

    env:
      MATRIX_RAILS_VERSION: ${{ matrix.rails }}
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install dependencies
      run: |
        bundle install
        bundle exec appraisal install
    - name: Run tests
      run: bundle exec appraisal rails-${{ matrix.rails }} rake test
